name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-GitHub-Actions
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          docker build -t fastapi-example .
      - name: Prepare Docker Image
        run: |
          docker tag fastapi-example caspin30/fastapi-example:v1
      -name: Publish Docker Image
        run: |
          docker push caspin30/fastapi-example:v1
